import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import Decrement from "../components/Decrement";
import Increment from "../components/Increment";
import { wrapper } from "../store";
import { initialize } from "../store/counter/slice";
import styles from "../styles/Home.module.css";

// export const getServerSideProps: GetServerSideProps =  async () => {
//   const data = 100;
//   return {
//     props: {
//       initialValue: data,
//     },
//   };
// };

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    await store.dispatch(initialize(233));

    console.log("State on server", store.getState());

    return {
      props: {},
    };
  }
);

const Home: NextPage<{ initialValue: number }> = ({ initialValue }) => {
  const dispatch = useDispatch();

  // useEffect(() => {
  //   dispatch(initialize(initialValue));
  // }, []);

  const value = useSelector((state: any) => state.counter.value);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello world, the current value is {value}</main>
      <Increment />
      <Decrement />
      <Link href="/gambling">Go to Gamble</Link>
    </div>
  );
};

export default Home;
